version: 2

sources:
  - name: duck_lake
    tables: 
      - name: pond_sessions
        description: Each row from each GA File Dump represents a session. The column within that file containing pageview information has been used to create its own table.
        meta: 
          dagster: 
            asset_key: ["pond_sessions"]
            auto_materialize_policy: 
              type: eager 
        columns: 
          - name: user_id
          - name: session_id
          - name: session_start_time 
          - name: session_sequence_number 
          - name: session_date
          - name: session_pageview_cnt
          - name: session_order_cnt
          - name: session_revenue 
          - name: session_total_revenue 
          - name: session_is_first_visit
          - name: session_duration
          - name: session_os 
          - name: session_is_mobile
          - name: session_device_category
          - name: session_browser
          - name: session_landing_screen 
          - name: session_exit_screen
          - name: session_source
          - name: session_medium
          - name: session_marketing_channel
          - name: session_city
          - name: session_region
          - name: session_country 

      - name: pond_pageviews
        description: This table was created by unpacking the pageview column from the sessions table. The original column was named hits and had more information in it. I only extracted page information and if those pages displayed products or not. 
        meta: 
          dagster: 
            asset_key: ["pond_pageviews"]
            auto_materialize_policy: 
              type: eager 
        columns:
          - name: pageview_id
          - name: pageview_timestamp
          - name: user_id
          - name: session_id
          - name: session_start_time
          - name: page_title 
          - name: hostname
          - name: page_path
            description: Each page path is split into parts by the forward slash value. This is the first part of the path coming after the hostname.  
          - name: page_path_level_1
            description: Each page path is split into parts by the forward slash value. This is the second part of the path coming after the first path value.
          - name: page_path_level_2
            description: Each page path is split into parts by the forward slash value. This is the third part of the path coming after the second path value.
          - name: page_path_level_3
            description: Each page path is split into parts by the forward slash value. This is the fourth part of the path coming after the third path value.
          - name: page_path_level_4 
            description: Each page path is split into parts by the forward slash value. This is the fifth part of the path coming after the fourth path value.
          - name: total_product_impressions 
            description: This is the total number of products displayed on the page.